#!/bin/bash
# sed -i -e 's/\r$//' scriptname.sh

port_offset=0

AUTHOR=${AUTHOR}
WWW=${WWW:-"/var/www"}
WEB_HOME=${WEB_HOME:-"/var/www/html"}
GITHUB_DOMAIN=${GITHUB_DOMAIN:-'https://github.com'}

INSTALL_DIR=${INSTALL_DIR:-"/usr/share"}

POSTGRESQL_RELEASES="11 12 13 14"
POSTGIS_RELEASES="2.4 2.5 3"
POSTGRESQL_DEFAULT_VERSION=${POSTGRESQL_DEFAULT_VERSION:-"14"}
POSTGIS_DEFAULT_VERSION=${POSTGIS_DEFAULT_VERSION:-"3.3"}


TOMCAT_RELEASES="7 8 9"
TOMCAT_DEFAULT_VERSION=${TOMCAT_DEFAULT_VERSION:-"8"}

FCREPO_RELEASES="5.1.1 4.7.5"
FCREPO_DEFAULT_VERSION=${FCREPO_DEFAULT_VERSION:-"4.7.5"}

FUSEKI_RELEASES="4.6.1 4.1.0 3.14.0"
FUSEKI_DEFAULT_VERSION=${FUSEKI_DEFAULT_VERSION:-"4.6.1"}

BLAZEGRAPH_RELEASES="2.1.5 2.1.6"
BLAZEGRAPH_DEFAULT_VERSION=${BLAZEGRAPH_DEFAULT_VERSION:-"2.1.6"}

KEYCLOAK_RELEASES="14.0.0 13.0.0 12.0.0 11.0.0 9.0.1 8.0.2"
KEYCLOAK_DEFAULT_VERSION=${KEYCLOAK_DEFAULT_VERSION:-"8.0.2"}


MYSQL_RELEASES="5 8"
MYSQL_DEFAULT_VERSION=${MYSQL_DEFAULT_VERSION:-"8"}

SORL_RELEASES="7 8"
SORL_DEFAULT_VERSION=${SORL_DEFAULT_VERSION:-"8"}

PHP_DEFAULT_VERSION=${PHP_DEFAULT_VERSION:-7.4}
